openapi: 3.0.0
info:
  title: Calculator API
  description: A simple calculator API that performs basic arithmetic operations and allows token generation.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /calculate:
    post:
      tags:
        - Calculator
      summary: Perform an arithmetic operation on two numbers.
      operationId: calculate
      parameters:
        - name: Operation
          in: header
          style: simple
          explode: false
          required: true
          schema:
            type: string
            enum:
              - add
              - subtract
              - multiply
              - divide
          description: The arithmetic operation to perform.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CalcNum"
        required: true
      responses:
        "200":
          description: Operation result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OperationResult"
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
      security:
        - bearerAuth: []
      x-swagger-router-controller: Calculator
  /token:
    get:
      tags:
        - Token
      summary: Generate a JWT token.
      operationId: generateToken
      responses:
        "200":
          description: A JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
      x-swagger-router-controller: Auth
components:
  schemas:
    CalcNum:
      type: object
      properties:
        num1:
          type: number
        num2:
          type: number
      required:
        - num1
        - num2
    OperationResult:
      type: object
      properties:
        result:
          type: number
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
